#!/usr/bin/env bash

sudo apt update && sudo apt upgrade -y
sudo apt install wget -y

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo apt install ./google-chrome-stable_current_amd64.deb

rm ./google-chrome-stable_current_amd64.deb

sudo apt install -f
