#!/usr/bin/env bash

set -e 

print_line() {
    echo "========================================="
}

run_step() {
    local message="$1"
    shift

    print_line
    echo "▶ START: $message"
    print_line

    "$@" 

    print_line
    echo "✔ COMPLETED: $message"
    print_line
    echo
}

// Installing Build Essentials
run_step "Installing Build Essentials" bash ./dev-tool/install-build-essentials

# Browsers
run_step "Installing Chrome" bash ./browser/install-chrome
run_step "Installing Firefox" bash ./browser/install-firefox
run_step "Installing LibreWolf" bash ./browser/install-librewolf

# IDE
run_step "Installing Cursor" bash ./ide/install-cursor
run_step "Installing VS Code" bash ./ide/install-vscode

# Dev Tools
run_step "Installing Node, NPM & PNPM" bash ./dev-tool/install-js
run_step "Installing uv" bash ./dev-tool/install-uv
#run_step "Installing Pyenv" bash ./dev-tool/install-pyenv
#run_step "Setting global python version" bash ./dev-tool/set-latest-python
run_step "Installing Goalng" bash ./dev-tool/install-golang
run_step "Installing Rust" bash ./dev-tool/install-rust
run_step "Installing CUDA" bash ./dev-tool/install-cuda
run_step "Installing Cloud Tools" bash ./dev-tool/install-cloud-tools
